### ISSUE TITLE
Unit Testing: Middleware Wallet Publisher

### ISSUE THREAD

**Issue by jorgeejgonzalez** [bitDubai/fermat#1397]
Es necesario elaborar las pruebas unitarias del modulo **fermat-dmp-plugin-middleware-wallet-publisher-bitdubai**

[Lineamientos para las Pruebas Unitarias](https://github.com/jorgeejgonzalez/fermat/wiki/Unit-Testing)

**Comment by acostarodrigo** [comment]
implementado
