### ISSUE TITLE
Asset Distribution - Genere cryptoAddress on Asset User Integration Test

### ISSUE THREAD

**Issue by acostarodrigo** [bitDubai/fermat#1915]
Goal: connect asset user and get Crypto Address.
1) generate at least two registrations of asset users by starting the user community sub app
2) Once the users are registered and visible from each device, generate a connection between them to request the crypto address and store it locally.

**Comment by nindriago** [comment]
Finish process, close issue please.

**Comment by acostarodrigo** [comment]
Close Issue
