### ISSUE TITLE
CBP - Reference Wallet - Crypto Customer - GUI - Navigation Drawer

### ISSUE THREAD

**Issue by nelsonalfo** [bitDubai/fermat#1934]
Implementacion del Navigation Drawer que permite acceder a las diferentes actividades de la Crypto Customer Wallet. basado en el Issue **Crypto Customer Wallet Design / Navigation Drawer** (https://github.com/bitDubai/fermat-graphic-design/issues/251) creado por @Neoperol 

@jorgeejgonzalez 

Issue Padre: #1910

**Comment by arnaldos** [comment]
@nelsonalfo @gregory propuesta para **Crypto Customer Wallet Design / Navigation Drawer**

![view_navigation](https://cloud.githubusercontent.com/assets/13594347/11314865/3254cdfa-8fbc-11e5-8321-35ff48b68924.jpg)

**Comment by arnaldos** [comment]
@nelsonalfo @gregory @Luis-Fernando-Molina propuesta para **Crypto Customer Wallet Design / Navigation Drawer**

![view_navigation](https://cloud.githubusercontent.com/assets/13594347/11314865/3254cdfa-8fbc-11e5-8321-35ff48b68924.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Desde abajo del nombre para abajo esta bien. 
Dale mas notoriedad al logo.
El nombre y la foto replantealo please.

**Comment by Luis-Fernando-Molina** [comment]
En la parte donde está el logo, quizás @jonathanborges3d se pueda lucir con algo artístico tomando el logo como base.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  nos mudamos de enlace para este que esta el mockup base de donde parte el drower https://github.com/bitDubai/fermat-graphic-design/issues/251#event-450540472
