### ISSUE TITLE
CBP - Reference Wallet - Crypto Customer - GUI - Open Negotiation Tab

### ISSUE THREAD

**Issue by nelsonalfo** [bitDubai/fermat#1939]
Implementacion del tab de Negociaciones en la actividad Home donde se puede ver la lista de negociaciones abiertas que lleva un customer. Basado en el Issue **Crypto Customer Wallet Design / Home view Design** (https://github.com/bitDubai/fermat-graphic-design/issues/219) creado por @Neoperol

@jorgeejgonzalez

Issue Padre: #1910

**Comment by arnaldos** [comment]
@m471c4

**Comment by nelsonalfo** [comment]
![customer wallet - home - negotiations](https://cloud.githubusercontent.com/assets/1823627/11384163/ba7edc04-92df-11e5-8e7b-75ab1d2bdabb.png)

![customer wallet - home - negotiations colaps](https://cloud.githubusercontent.com/assets/1823627/11384164/ba8d839e-92df-11e5-9e24-c23c58b31a89.png)
