### ISSUE TITLE
CBP - Reference Wallet - Crypto Customer - GUI - Open Contract Tab

### ISSUE THREAD

**Issue by nelsonalfo** [bitDubai/fermat#1940]
Implementacion del tab de Contratos en la actividad Home donde se puede ver la lista de contratos abiertos que lleva un customer. Basado en el Issue **Crypto Customer Wallet Design / Home Contract Tab view Design** (https://github.com/bitDubai/fermat-graphic-design/issues/254) creado por @Neoperol

@jorgeejgonzalez

Issue Padre: #1910

**Comment by arnaldos** [comment]
@m471c4

**Comment by nelsonalfo** [comment]
![customer wallet - home - contracts](https://cloud.githubusercontent.com/assets/1823627/11379521/eaf0efb6-92c2-11e5-9e54-29525159541e.png)

![customer wallet - home - contracts colapse](https://cloud.githubusercontent.com/assets/1823627/11379522/eb005154-92c2-11e5-97b8-ab2d7345ac6f.png)

Hay que corregir el *Action Bar*
