### ISSUE TITLE
CBP - Reference Wallet - Crypto Customer - GUI - Contract History Activity

### ISSUE THREAD

**Issue by nelsonalfo** [bitDubai/fermat#1941]
Implementación de la actividad Contract History que permite ver la lista de contratos cerrados o cancelados. Basado en el Issue **Crypto Customer Wallet Design / Contract list view Design #255** creado por @Neoperol en el repositorio **bitDubai/fermat-graphic-design**

@jorgeejgonzalez

Issue Padre: #1910

**Comment by arnaldos** [comment]
@m471c4

**Comment by nelsonalfo** [comment]
![customer wallet - contract history](https://cloud.githubusercontent.com/assets/1823627/11379462/a9979e66-92c2-11e5-9198-323f6d28f5b2.png)

![customer wallet - contract history - filter list](https://cloud.githubusercontent.com/assets/1823627/11379463/a9a91092-92c2-11e5-8484-ea9cdf1f3d1a.png)
