### ISSUE TITLE
CBP - Reference Wallet - Crypto Customer - GUI - Settings Activity

### ISSUE THREAD

**Issue by nelsonalfo** [bitDubai/fermat#1943]
Implementación de la actividad *Settings* que permite configurar diferentes aspectos de la wallet como lo son: *locaciones de entrega, cuentas de banco, asociación con otra wallet y monedas de interés*. Basado en el Issue **Crypto Customer Wallet Design / Settings view Design #253** creado por @Neoperol en el repositorio **bitDubai/fermat-graphic-design**

@jorgeejgonzalez

Issue Padre: #1910

**Comment by arnaldos** [comment]
@m471c4
