### ISSUE TITLE
CBP - Reference Wallet - Crypto Customer - GUI - Start Negotiation Activity

### ISSUE THREAD

**Issue by nelsonalfo** [bitDubai/fermat#1945]
Implementación de la actividad *Start Negotiation* que permite iniciar una nueva negociación con un broker previamente seleccionado completando una serie de pasos o clausulas. Basado en el Issue **Crypto Customer Wallet Design / Start of Negotiation view Design** (https://github.com/bitDubai/fermat-graphic-design/issues/252) creado por @Neoperol

@jorgeejgonzalez

Issue Padre: #1910

**Comment by arnaldos** [comment]
@m471c4

**Comment by nelsonalfo** [comment]
Ya se implementó y recibió feedback, faltan son detalles menores
