### ISSUE TITLE
CBP - Reference Wallet - Crypto Customer - GUI - Wizard Identity

### ISSUE THREAD

**Issue by nelsonalfo** [bitDubai/fermat#1946]
Implementación del *Wizard Identity* que ha de aparecer la primera vez que se abre la wallet y permite asociar una identidad con la wallet. Basado en el Issue **Crypto Customer Wallet Design / Wizard Identity view Design** (https://github.com/bitDubai/fermat-graphic-design/issues/259) creado por @Neoperol

@jorgeejgonzalez

Issue Padre: #1910

**Comment by arnaldos** [comment]
@m471c4

**Comment by nelsonalfo** [comment]
Ya no va, pero ya esta implementada y funcional en caso de ser nuevamente requerida
