### ISSUE TITLE
CBP - Reference Wallet - Crypto Customer - GUI - Close Contract Details Activity

### ISSUE THREAD

**Issue by nelsonalfo** [bitDubai/fermat#1953]
Implementación de la actividad *Close Contract Details* que permite ver el detalle de un contrato abierto, donde el customer puede ver el resumen de un contrato que haya sido cerrado porque fue exitoso, porque se cancelo una negociación o porque no se cumplió con los términos del contrato.

@jorgeejgonzalez 
@Neoperol 

Issue Padre: #1910

**Comment by arnaldos** [comment]
@m471c4

**Comment by nelsonalfo** [comment]
Ya se implementó, falta feedback
