### ISSUE TITLE
README-PLUG-INS.MD

### ISSUE THREAD

**Issue by daveo90** [bitDubai/fermat#2881]
starting to review readme-plug-ins.md @Luis-Fernando-Molina

**Comment by daveo90** [comment]
Hello finished this @Luis-Fernando-Molina

**Comment by daveo90** [comment]
lo de traducir me lo dice por si encuentro algo, o obvie algo en el texto? @Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
:+1:
