### ISSUE TITLE
README-GUI.md

### ISSUE THREAD

**Issue by daveo90** [bitDubai/fermat#2884]
reviewing readme-gui.md @Luis-Fernando-Molina

**Comment by daveo90** [comment]
Hola @Luis-Fernando-Molina a que se refiere en esta oracion la palabra leyenda? 
Un proyecto GUI Component para Android en fermat tiene la siguiente estructura basica (Leyenda: + carpeta, > paquete, - archivo):

**Comment by Luis-Fernando-Molina** [comment]
preguntale a @furszy por favor que el lo escribio.

**Comment by furszy** [comment]
La leyenda es la descripción de lo que significan los símbolos, el "+" son carpetas, ">" son paquetes, "-" son archivos. Estos símbolos se usan para hacer el recorrido de los componentes GUI.

**Comment by daveo90** [comment]
muchas gracias @furszy

**Comment by daveo90** [comment]
@Luis-Fernando-Molina listo terminado
