### ISSUE TITLE
Network Service Crypto Addresses - Testing

### ISSUE THREAD

**Issue by wildeivid** [bitDubai/fermat#3043]
Test Crypto Addresses CCP

##### test of connections closing and reception notifications

@furszy please assign this issue to me.

**Comment by nattyco** [comment]
Cuando le pide la direccion al intra user se ve este error

 ********* Crypto Addresses: Executor Agent -> Sending REQUEST. CryptoAddressesNetworkServiceCryptoAddressRequest{requestId=15980278-ed35-41e3-89e4-5171b7b196da, walletPublicKey='reference_wallet', identityTypeRequesting=INTRA_USER, identityTypeResponding=INTRA_USER, identityPublicKeyRequesting='04D5DA738B4D71D81366C1D6A82CA74E1BEF6FFD11EDB5568A355BCFA239231B76C479BE3FB69B7502F326B7A2525C66E3ECB4C032DE0CB2FB691A821F59ABFA52', identityPublicKeyResponding='0431E7C786AF8ED76238184515E1FBDA6080CD9F4F07EAEC302E020B951E6930EE3EADFE7F02F371121C29FEE7DD465E8D03049B84CAE2721ED58972C8E6FF0E32', cryptoCurrency=BITCOIN, cryptoAddress=com.bitdubai.fermat_api.layer.all_definition.money.CryptoAddress@3c091309, state=PROCESSING_SEND, type=SENT, action=REQUEST, cryptoAddressDealer=CRYPTO_WALLET, blockchainNetworkType=TEST}
11-27 18:05:29.539    2317-5277/com.bitdubai.fermat I/System.out﹕ mensaje enviado
11-27 18:05:29.816    2317-5314/com.bitdubai.fermat I/System.out﹕ WsCommunicationVPNClient - sendMessage
11-27 18:05:30.178    2317-5292/com.bitdubai.fermat I/System.out﹕ WsCommunicationVPNClientManagerAgent - vpnClientActiveCache.size() 2
11-27 18:05:30.178    2317-5292/com.bitdubai.fermat I/System.out﹕ WsCommunicationVPNClientManagerAgent - vpnClientActiveCache.get(CRYPTO_ADDRESSES).size() = 1
11-27 18:05:30.178    2317-5292/com.bitdubai.fermat I/System.out﹕ WsCommunicationVPNClientManagerAgent - vpnClientActiveCache.get(INTRA_USER).size() = 1
11-27 18:05:30.768    2317-5311/com.bitdubai.fermat I/System.out﹕ ---------------------------------------------------------------------
11-27 18:05:30.768    2317-5311/com.bitdubai.fermat I/System.out﹕ WsCommunicationVPNClient - Starting method onClose
11-27 18:05:30.768    2317-5311/com.bitdubai.fermat I/System.out﹕ WsCommunicationVPNClient -  code   = 1000 reason =  remote = false
11-27 18:05:30.770    2317-5313/com.bitdubai.fermat W/System.err﹕ ========================================================================================================================================================
11-27 18:05:30.770    2317-5313/com.bitdubai.fermat W/System.err﹕ Fermat Error Manager * Unexpected Exception Report
11-27 18:05:30.770    2317-5313/com.bitdubai.fermat W/System.err﹕ ========================================================================================================================================================
11-27 18:05:30.770    2317-5313/com.bitdubai.fermat W/System.err﹕ Source: PluginVersionReference{pluginDeveloperReference=PluginDeveloperReference{pluginReference=PluginReference{layerReference=LayerReference{platformReference=PlatformReference{, platform=CRYPTO_CURRENCY_PLATFORM}, layer=NETWORK_SERVICE}, plugin=CRYPTO_ADDRESSES}, developer=BITDUBAI}, version=1.0.0}
11-27 18:05:30.770    2317-5313/com.bitdubai.fermat W/System.err﹕ Severity: DISABLES_SOME_FUNCTIONALITY_WITHIN_THIS_PLUGIN
11-27 18:05:30.770    2317-5313/com.bitdubai.fermat W/System.err﹕ ********************************************************************************************************************************************************
11-27 18:05:30.770    2317-5313/com.bitdubai.fermat W/System.err﹕ Exception Number: 1
11-27 18:05:30.770    2317-5313/com.bitdubai.fermat W/System.err﹕ Exception Type: class java.lang.Exception
11-27 18:05:30.770    2317-5313/com.bitdubai.fermat W/System.err﹕ Exception Message: Can not sleep
11-27 18:05:30.770    2317-5313/com.bitdubai.fermat W/System.err﹕ Exception Possible Cause: N/A
11-27 18:05:30.770    2317-5313/com.bitdubai.fermat W/System.err﹕ Exception Context:
11-27 18:05:30.770    2317-5313/com.bitdubai.fermat W/System.err﹕ ---------------------------------------------------------------------------------
11-27 18:05:30.770    2317-5313/com.bitdubai.fermat W/System.err﹕ N/A
11-27 18:05:30.770    2317-5313/com.bitdubai.fermat W/System.err﹕ ---------------------------------------------------------------------------------
11-27 18:05:30.770    2317-5313/com.bitdubai.fermat W/System.err﹕ Exception Stack Trace:
11-27 18:05:30.770    2317-5313/com.bitdubai.fermat W/System.err﹕ ---------------------------------------------------------------------------------
11-27 18:05:30.770    2317-5313/com.bitdubai.fermat W/System.err﹕ Class: com.bitdubai.fermat_p2p_api.layer.all_definition.common.network_services.template.structure.CommunicationNetworkServiceRemoteAgent - Line: 231
11-27 18:05:30.770    2317-5313/com.bitdubai.fermat W/System.err﹕ Class: com.bitdubai.fermat_p2p_api.layer.all_definition.common.network_services.template.structure.CommunicationNetworkServiceRemoteAgent - Line: 46
11-27 18:05:30.770    2317-5313/com.bitdubai.fermat W/System.err﹕ Class: com.bitdubai.fermat_p2p_api.layer.all_definition.common.network_services.template.structure.CommunicationNetworkServiceRemoteAgent$1 - Line: 104
11-27 18:05:30.770    2317-5313/com.bitdubai.fermat W/System.err﹕ Class: java.lang.Thread - Line: 818
11-27 18:05:30.770    2317-5313/com.bitdubai.fermat W/System.err﹕ ---------------------------------------------------------------------------------
11-27 18:05:30.770    2317-5313/com.bitdubai.fermat W/System.err﹕ Exceptions Processed: 1
11-27 18:05:30.770    2317-5313/com.bitdubai.fermat W/System.err﹕ ========================================================================================================================================================
11-27 18:05:30.772    2317-5314/com.bitdubai.fermat W/System.err﹕ ========================================================================================================================================================
11-27 18:05:30.772    2317-5314/com.bitdubai.fermat W/System.err﹕ Fermat Error Manager * Unexpected Exception Report
11-27 18:05:30.772    2317-5314/com.bitdubai.fermat W/System.err﹕ ========================================================================================================================================================
11-27 18:05:30.772    2317-5314/com.bitdubai.fermat W/System.err﹕ Source: PluginVersionReference{pluginDeveloperReference=PluginDeveloperReference{pluginReference=PluginReference{layerReference=LayerReference{platformReference=PlatformReference{, platform=CRYPTO_CURRENCY_PLATFORM}, layer=NETWORK_SERVICE}, plugin=CRYPTO_ADDRESSES}, developer=BITDUBAI}, version=1.0.0}
11-27 18:05:30.772    2317-5314/com.bitdubai.fermat W/System.err﹕ Severity: DISABLES_SOME_FUNCTIONALITY_WITHIN_THIS_PLUGIN
11-27 18:05:30.772    2317-5314/com.bitdubai.fermat W/System.err﹕ ********************************************************************************************************************************************************
11-27 18:05:30.772    2317-5314/com.bitdubai.fermat W/System.err﹕ Exception Number: 1
11-27 18:05:30.772    2317-5314/com.bitdubai.fermat W/System.err﹕ Exception Type: class java.lang.InterruptedException
11-27 18:05:30.773    2317-5314/com.bitdubai.fermat W/System.err﹕ Exception Message: null
11-27 18:05:30.773    2317-5314/com.bitdubai.fermat W/System.err﹕ Exception Possible Cause: N/A
11-27 18:05:30.773    2317-5314/com.bitdubai.fermat W/System.err﹕ Exception Context:
11-27 18:05:30.773    2317-5314/com.bitdubai.fermat W/System.err﹕ ---------------------------------------------------------------------------------
11-27 18:05:30.773    2317-5314/com.bitdubai.fermat W/System.err﹕ N/A
11-27 18:05:30.773    2317-5314/com.bitdubai.fermat W/System.err﹕ ---------------------------------------------------------------------------------
11-27 18:05:30.773    2317-5314/com.bitdubai.fermat W/System.err﹕ Exception Stack Trace:
11-27 18:05:30.773    2317-5314/com.bitdubai.fermat W/System.err﹕ ---------------------------------------------------------------------------------
11-27 18:05:30.773    2317-5314/com.bitdubai.fermat W/System.err﹕ Class: java.lang.Thread - Line: -2
11-27 18:05:30.773    2317-5314/com.bitdubai.fermat W/System.err﹕ Class: java.lang.Thread - Line: 1031
11-27 18:05:30.773    2317-5314/com.bitdubai.fermat W/System.err﹕ Class: java.lang.Thread - Line: 985
11-27 18:05:30.773    2317-5314/com.bitdubai.fermat W/System.err﹕ Class: com.bitdubai.fermat_p2p_api.layer.all_definition.common.network_services.template.structure.CommunicationNetworkServiceRemoteAgent - Line: 308
11-27 18:05:30.773    2317-5314/com.bitdubai.fermat W/System.err﹕ Class: com.bitdubai.fermat_p2p_api.layer.all_definition.common.network_services.template.structure.CommunicationNetworkServiceRemoteAgent$2 - Line: 113
11-27 18:05:30.773    2317-5314/com.bitdubai.fermat W/System.err﹕ Class: java.lang.Thread - Line: 818

**Comment by furszy** [comment]
Closed
