### ISSUE TITLE
GUI - Desktop - Screen

### ISSUE THREAD

**Issue by furszy** [bitDubai/fermat#3153]
Se debe implementar la vista del dekstop.

**Comment by furszy** [comment]
Vista implementada.

**Comment by Luis-Fernando-Molina** [comment]
@furszy avisame cuando pueda bajar la APP de nuevo... o la reemplazas todas las noches?

**Comment by furszy** [comment]
@Luis-Fernando-Molina cuando subo a develop subo el apk, todavía tengo cambios en mi repo para mezclar.
