### ISSUE TITLE
CCP - stock Transactions - Hold  - Analisys

### ISSUE THREAD

**Issue by franklinmarcano1970** [bitDubai/fermat#3156]
This is the Analisys root. It is closed whenever all analisys is done. This issue must be linked to the root of the issue structure.
@nelsonalfo please assign this issue to me.

**Comment by Luis-Fernando-Molina** [comment]
@nelsonalfo y @franklinmarcano1970 Esta transaccion no puede ir en la capa Stock Transactions en la plataforma CCP. Esta plataforma no conoce el concepto de stock es algo de mas arriba. Debe ir en la capa de Crypto Transactions al lado del resto de las que están alli. Lo mismo sucede con CASH y BANK , debe ir en la capa transaccional que ya tiene cada una.
