### ISSUE TITLE
Reference Wallet don't show Sent Transactions

### ISSUE THREAD

**Issue by nattyco** [bitDubai/fermat#3380]
No se estan mostrando los envios a otro intra user en el tab Sent, en el log se ve este error

W/System.err﹕ Fermat Error Manager * Unexpected Exception Report
11-24 14:04:35.860    1507-1507/com.bitdubai.fermat W/System.err﹕ ========================================================================================================================================================
11-24 14:04:35.860    1507-1507/com.bitdubai.fermat W/System.err﹕ Source: CWP_WALLET_RUNTIME_WALLET_BITCOIN_WALLET_ALL_BITDUBAI
11-24 14:04:35.861    1507-1507/com.bitdubai.fermat W/System.err﹕ Severity: DISABLES_THIS_FRAGMENT
11-24 14:04:35.861    1507-1507/com.bitdubai.fermat W/System.err﹕ ********************************************************************************************************************************************************
11-24 14:04:35.862    1507-1507/com.bitdubai.fermat W/System.err﹕ Exception Number: 1
11-24 14:04:35.862    1507-1507/com.bitdubai.fermat W/System.err﹕ Exception Type: class java.lang.NullPointerException
11-24 14:04:35.863    1507-1507/com.bitdubai.fermat W/System.err﹕ Exception Message: Attempt to invoke virtual method 'void android.widget.LinearLayout.getLocationOnScreen(int[])' on a null object reference
11-24 14:04:35.864    1507-1507/com.bitdubai.fermat W/System.err﹕ Exception Possible Cause: N/A
11-24 14:04:35.864    1507-1507/com.bitdubai.fermat W/System.err﹕ Exception Context:
11-24 14:04:35.865    1507-1507/com.bitdubai.fermat W/System.err﹕ ---------------------------------------------------------------------------------
11-24 14:04:35.865    1507-1507/com.bitdubai.fermat W/System.err﹕ N/A
11-24 14:04:35.865    1507-1507/com.bitdubai.fermat W/System.err﹕ ---------------------------------------------------------------------------------
11-24 14:04:35.866    1507-1507/com.bitdubai.fermat W/System.err﹕ Exception Stack Trace:
11-24 14:04:35.866    1507-1507/com.bitdubai.fermat W/System.err﹕ ---------------------------------------------------------------------------------
11-24 14:04:35.866    1507-1507/com.bitdubai.fermat W/System.err﹕ Class: com.bitdubai.reference_niche_wallet.bitcoin_wallet.fragments.wallet_final_version.SendTransactionFragment2 - Line: 159
11-24 14:04:35.866    1507-1507/com.bitdubai.fermat W/System.err﹕ Class: com.bitdubai.reference_niche_wallet.bitcoin_wallet.fragments.wallet_final_version.SendTransactionFragment2 - Line: 151
11-24 14:04:35.866    1507-1507/com.bitdubai.fermat W/System.err﹕ Class: com.bitdubai.reference_niche_wallet.bitcoin_wallet.fragments.wallet_final_version.SendTransactionFragment2 - Line: 142

https://github.com/bitDubai/fermat/issues/2477

@furszy assign this issue

**Comment by furszy** [comment]
issue completado.
