### ISSUE TITLE
Outgoing Intra Actor Transaction - Vault return InsufficientCryptoFundsException

### ISSUE THREAD

**Issue by nattyco** [bitDubai/fermat#3507]
Despues de hacer varios envios y ver que tengo fondos en la wallet available balance y book balance al hacer otro envio de btc me da error de fondos insuficientes, al ejecutar el metodos sendbitcoins de la cryptoVaultManager

@furszy  assing that

**Comment by acostarodrigo** [comment]
lo veo, pero seguramente el problema e que no es correcto tener balance available en la wallet.
como lo puedo reproducir?

algo que estamos manejando mal es el fee, que no se está descontando del balance. actualmente estamos incluyendo un fee de unos 10000 satoshis...si el balance es inferior a ese, ese puede ser el error.

**Comment by acostarodrigo** [comment]
Fixed
