### ISSUE TITLE
Reference Wallet - Error creating new Identity

### ISSUE THREAD

**Issue by nattyco** [bitDubai/fermat#3512]
Si no tengo identity cuando voy a la wallet me dice que tengo que crear una al usar esa opcion se cae la app.

@furszy assign that

12-01 11:28:43.512    5530-5530/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.bitdubai.fermat, PID: 5530
    java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String com.bitdubai.fermat_android_api.layer.definition.wallet.interfaces.SubAppsSession.getAppPublicKey()' on a null object reference
            at com.bitdubai.sub_app.intra_user_identity.fragments.IntraUserIdentityListFragment$1.onClick(IntraUserIdentityListFragment.java:76)
            at android.view.View.performClick(View.java:4756)
            at android.view.View$PerformClick.run(View.java:19749)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

12-01 11:28:41.608    5530-5530/? W/System.err﹕ java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String com.bitdubai.fermat_api.layer.dmp_module.wallet_manager.InstalledSubApp.getAppPublicKey()' on a null object reference
12-01 11:28:41.609    5530-5530/? W/System.err﹕ at com.bitdubai.sub_app.intra_user_identity.session.IntraUserIdentitySubAppSession.<init>(IntraUserIdentitySubAppSession.java:50)
12-01 11:28:41.609    5530-5530/? W/System.err﹕ at com.bitdubai.android_core.app.common.version_1.Sessions.SubAppSessionManager.openSubAppSession(SubAppSessionManager.java:82)
12-01 11:28:41.609    5530-5530/? W/System.err﹕ at com.bitdubai.android_core.app.SubAppActivity.createOrCallSubAppSession(SubAppActivity.java:562)
12-01 11:28:41.609    5530-5530/? W/System.err﹕ at com.bitdubai.android_core.app.SubAppActivity.onCreate(SubAppActivity.java:76)
12-01 11:28:41.609    5530-5530/? W/System.err﹕ at android.app.Activity.performCreate(Activity.java:5933)
12-01 11:28:41.609    5530-5530/? W/System.err﹕ at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
12-01 11:28:41.609    5530-5530/? W/System.err﹕ at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
12-01 11:28:41.609    5530-5530/? W/System.err﹕ at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
12-01 11:28:41.609    5530-5530/? W/System.err﹕ at android.app.ActivityThread.access$800(ActivityThread.java:144)
12-01 11:28:41.609    5530-5530/? W/System.err﹕ at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
12-01 11:28:41.610    5530-5530/? W/System.err﹕ at android.os.Handler.dispatchMessage(Handler.java:102)
12-01 11:28:41.610    5530-5530/? W/System.err﹕ at android.os.Looper.loop(Looper.java:135)
12-01 11:28:41.610    5530-5530/? W/System.err﹕ at android.app.ActivityThread.main(ActivityThread.java:5221)
12-01 11:28:41.610    5530-5530/? W/System.err﹕ at java.lang.reflect.Method.invoke(Native Method)
12-01 11:28:41.610    5530-5530/? W/System.err﹕ at java.lang.reflect.Method.invoke(Method.java:372)
12-01 11:28:41.610    5530-5530/? W/System.err﹕ at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
12-01 11:28:41.610    5530-5530/? W/System.err﹕ at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
12-01 11:28:41.611    5530-5530/? W/System.err﹕ ========================================================================================================================================================
12-01 11:28:41.611    5530-5530/? W/System.err﹕ Fermat Error Manager * Unexpected Exception Report
12-01 11:28:41.611    5530-5530/? W/System.err﹕ ========================================================================================================================================================
12-01 11:28:41.611    5530-5530/? W/System.err﹕ Source: ACTIVITY
12-01 11:28:41.611    5530-5530/? W/System.err﹕ Severity: UNSTABLE
12-01 11:28:41.611    5530-5530/? W/System.err﹕ ********************************************************************************************************************************************************
12-01 11:28:41.611    5530-5530/? W/System.err﹕ Exception Number: 1
12-01 11:28:41.611    5530-5530/? W/System.err﹕ Exception Type: class java.lang.NullPointerException
12-01 11:28:41.611    5530-5530/? W/System.err﹕ Exception Message: Attempt to invoke interface method 'java.lang.String com.bitdubai.fermat_api.layer.dmp_module.wallet_manager.InstalledSubApp.getAppPublicKey()' on a null object reference
12-01 11:28:41.611    5530-5530/? W/System.err﹕ Exception Possible Cause: N/A
12-01 11:28:41.611    5530-5530/? W/System.err﹕ Exception Context:
12-01 11:28:41.611    5530-5530/? W/System.err﹕ ---------------------------------------------------------------------------------
12-01 11:28:41.611    5530-5530/? W/System.err﹕ N/A
12-01 11:28:41.611    5530-5530/? W/System.err﹕ ---------------------------------------------------------------------------------
12-01 11:28:41.611    5530-5530/? W/System.err﹕ Exception Stack Trace:
12-01 11:28:41.611    5530-5530/? W/System.err﹕ ---------------------------------------------------------------------------------
12-01 11:28:41.611    5530-5530/? W/System.err﹕ Class: com.bitdubai.android_core.app.common.version_1.Sessions.SubAppSessionManager - Line: 123
12-01 11:28:41.611    5530-5530/? W/System.err﹕ Class: com.bitdubai.android_core.app.SubAppActivity - Line: 562
12-01 11:28:41.611    5530-5530/? W/System.err﹕ Class: com.bitdubai.android_core.app.SubAppActivity - Line: 76
12-01 11:28:41.611    5530-5530/? W/System.err﹕ Class: android.app.Activity - Line: 5933
12-01 11:28:41.611    5530-5530/? W/System.err﹕ Class: android.app.Instrumentation - Line: 1105
12-01 11:28:41.611    5530-5530/? W/System.err﹕ Class: android.app.ActivityThread - Line: 2251
12-01 11:28:41.611    5530-5530/? W/System.err﹕ Class: android.app.ActivityThread - Line: 2360
12-01 11:28:41.611    5530-5530/? W/System.err﹕ Class: android.app.ActivityThread - Line: 144
12-01 11:28:41.611    5530-5530/? W/System.err﹕ Class: android.app.ActivityThread$H - Line: 1278
12-01 11:28:41.611    5530-5530/? W/System.err﹕ Class: android.os.Handler - Line: 102
12-01 11:28:41.611    5530-5530/? W/System.err﹕ Class: android.os.Looper - Line: 135
12-01 11:28:41.612    5530-5530/? W/System.err﹕ Class: android.app.ActivityThread - Line: 5221
12-01 11:28:41.612    5530-5530/? W/System.err﹕ Class: java.lang.reflect.Method - Line: -2
12-01 11:28:41.612    5530-5530/? W/System.err﹕ Class: java.lang.reflect.Method - Line: 372
12-01 11:28:41.612    5530-5530/? W/System.err﹕ Class: com.android.internal.os.ZygoteInit$MethodAndArgsCaller - Line: 899
12-01 11:28:41.612    5530-5530/? W/System.err﹕ Class: com.android.internal.os.ZygoteInit - Line: 694
12-01 11:28:41.612    5530-5530/? W/System.err﹕ ---------------------------------------------------------------------------------
12-01 11:28:41.612    5530-5530/? W/System.err﹕ Exceptions Processed: 1
12-01 11:28:41.612    5530-5530/? W/System.err﹕ ========================================================================================================================================================
12-01 11:28:41.661    5530-5530/? I/Recycler Base﹕ recycler view setup
12-01 11:28:41.699    5530-5530/? W/System.err﹕ java.lang.NullPointerException: Attempt to invoke interface method 'java.util.List com.bitdubai.fermat_ccp_api.layer.identity.intra_user.interfaces.IntraWalletUserIdentityManager.getAllIntraWalletUsersFromCurrentDeviceUser()' on a null object reference
12-01 11:28:41.744    5530-5530/? W/System.err﹕ at com.bitdubai.sub_app.intra_user_identity.fragments.IntraUserIdentityListFragment.initViews(IntraUserIdentityListFragment.java:89)
12-01 11:28:41.745    5530-5530/? W/System.err﹕ at com.bitdubai.fermat_android_api.ui.fragments.FermatListFragment.onCreateView(FermatListFragment.java:61)
1

**Comment by furszy** [comment]
Issue completed.
