### ISSUE TITLE
Intra User Community - Error listing Request Notifications.

### ISSUE THREAD

**Issue by nattyco** [bitDubai/fermat#3514]
Al hacer solicitud de conexión entre intra users se ve la notificación de llegada de la solicitud en el celular pero al ir a la ventana de notificaciones no se ve la lista, en el log cat se ve este error.

En el logcat también se ve que esta tratando de reenviar el mensaje de conexión al otro intra user que cerro la conexión con el WS.

@furszy assign this issue.

12-01 11:40:24.889    2809-2809/com.bitdubai.fermat W/System.err﹕ Fermat Error Manager * Unexpected Exception Report
12-01 11:40:24.889    2809-2809/com.bitdubai.fermat W/System.err﹕ ========================================================================================================================================================
12-01 11:40:24.889    2809-2809/com.bitdubai.fermat W/System.err﹕ Source: ACTIVITY
12-01 11:40:24.889    2809-2809/com.bitdubai.fermat W/System.err﹕ Severity: CRASH
12-01 11:40:24.889    2809-2809/com.bitdubai.fermat W/System.err﹕ ********************************************************************************************************************************************************
12-01 11:40:24.889    2809-2809/com.bitdubai.fermat W/System.err﹕ Exception Number: 1
12-01 11:40:24.889    2809-2809/com.bitdubai.fermat W/System.err﹕ Exception Type: class java.lang.NullPointerException
12-01 11:40:24.889    2809-2809/com.bitdubai.fermat W/System.err﹕ Exception Message: Attempt to read from null array
12-01 11:40:24.889    2809-2809/com.bitdubai.fermat W/System.err﹕ Exception Possible Cause: N/A
12-01 11:40:24.890    2809-2809/com.bitdubai.fermat W/System.err﹕ Exception Context:
12-01 11:40:24.890    2809-2809/com.bitdubai.fermat W/System.err﹕ ---------------------------------------------------------------------------------
12-01 11:40:24.890    2809-2809/com.bitdubai.fermat W/System.err﹕ N/A
12-01 11:40:24.890    2809-2809/com.bitdubai.fermat W/System.err﹕ ---------------------------------------------------------------------------------
12-01 11:40:24.890    2809-2809/com.bitdubai.fermat W/System.err﹕ Exception Stack Trace:
12-01 11:40:24.890    2809-2809/com.bitdubai.fermat W/System.err﹕ ---------------------------------------------------------------------------------
12-01 11:40:24.890    2809-2809/com.bitdubai.fermat W/System.err﹕ Class: com.bitdubai.sub_app.intra_user_community.fragments.ConnectionsWorldFragment - Line: 135

**Comment by furszy** [comment]
Issue completed.
