### ISSUE TITLE
DAP - Wallet Module - Asset Issuer Wallet Module - Plug-in - Implementation

### ISSUE THREAD

**Issue by Yayotron** [bitDubai/fermat#3519]
The goal for this issue is to implement all the needed methods in the Asset Issuer Wallet Module to satisfy all the features for this wallet: http://ninjamock.com/s/QRH9T
The features were divided (by myself) in five sections to maintain a better organization; these features would be listed below:

       1. User list methods.
       2. User group methods.
       3. Asset distribution methods.
       4. Asset Statistic methods.
       5. Issuer Wallet methods.

Parent: #3656

**Comment by Yayotron** [comment]
@acostarodrigo please assign this to me.

**Comment by acostarodrigo** [comment]
despues explicame qué pensas asset en el 3 y el 5.

**Comment by acostarodrigo** [comment]
pensas *hacer (ya la palabra asset es la única que tengo en el cerebro)

**Comment by Yayotron** [comment]
AJAJAJAJAJAJA, el 3 abarca los métodos que tienen que ver con el distribution, principalmente con la selección de usuarios/grupos para distribuirle, y el propio método de distribuir.
Y el 5 tiene los métodos propios de la Issuer Wallet (cargar y crear).

**Comment by acostarodrigo** [comment]
el distribution espera un Mapa con el Asset y el usuario, vos lo que tenes que generar en el module de la wallet son las distintas opciones de selección del usuario.

No deberias tocar nada en el distributor-

**Comment by Yayotron** [comment]
No lo hago, los métodos son para preparar la lista de usuarios que se le enviarán al module, con esas opciones que decís (agregar un grupo completo, remover un usuario, etc.)

**Comment by Yayotron** [comment]
All the implementation is done, missing testing.
