### ISSUE TITLE
CCP - Intra Users -Community - Other profile view

### ISSUE THREAD

**Issue by josemanueldsds** [bitDubai/fermat#3774]
En el other profile de la community se muestra el campo de email del usuario, este campo debe ser removido y colocar en su lugar un mensaje de status o una frase que identifique al usuario, propuesta hecha por @Luis-Fernando-Molina

**Comment by josemanueldsds** [comment]
@furszy 
@Neoperol

**Comment by furszy** [comment]
A este issue hay que hacerle la parte de la plataforma para que tengan esos datos, @nattyco create los issues correspondientes.

**Comment by nattyco** [comment]
@furszy que datos se deben agregar? es sobre la identidad del intra user verdad.

**Comment by josemanueldsds** [comment]
Se oculto el campo de email de la vista, cuando se tenga listo el nuevo contenido me avisan por aqui para renderizarlo en la vista 
@furszy 
@nattyco

**Comment by furszy** [comment]
closed
