### ISSUE TITLE
CCP - Intra Users -Community -  Implement the cache in view explore

### ISSUE THREAD

**Issue by josemanueldsds** [bitDubai/fermat#3776]
Cuando se entra por primera ves en la vista de eplore se debe mostrar un progress dialog que indique que accion esta ocurriendo en la panta, al momento de cargar esa vista por segunda, se venga de la vista que sea, se debe mostrar la data guardada en cache para que en ningun momento se presente la pantalla negra vacia

**Comment by josemanueldsds** [comment]
@furszy

**Comment by furszy** [comment]
closed
