### ISSUE TITLE
CCP - Intra Users -Community -  Connections view

### ISSUE THREAD

**Issue by josemanueldsds** [bitDubai/fermat#3778]
en la vista de conection aparecen son las solicitudes de coneccion en lugar de las conexiones ya establecidas, es decir conecciones aceptadas de lado y lado, tanto de emisor como receptor, en tal caso las conexiones no establecidas o aceptadas de parte y parte se deberian mostar como pendientes

**Comment by josemanueldsds** [comment]
@furszy

**Comment by furszy** [comment]
closed
