### ISSUE TITLE
DatabaseTable method addSelectOperator() fully implementation

### ISSUE THREAD

**Issue by lnacosta** [bitDubai/fermat#3860]
We have a method to add select operators in our querys, but its not implemented the way to add this "selectOperator" in the query to get it.

We should implement this enhancement.

**Comment by lnacosta** [comment]
@pmgesualdi please solve this!

**Comment by pmgesualdi** [comment]
Changed "AndroidDatabaseSelectOperator" class name into "AndroidDatabaseAggregateFunction", and all subsequent "SelectOperator" names in methods, classes, and interfaces into "AggregateFunction".
The reason for this relies in that the functions that this components give are specific 'SQL Aggregate Funcitons' ('COUNT','MAX', etc.), and "Select Operator" wasn't specific enough.
