### ISSUE TITLE
CCP - Outgoing Intra Actor Transaction - QA - Bug #1

### ISSUE THREAD

**Issue by Yayotron** [bitDubai/fermat#4000]
While sending bitcoins through this transaction if the configured timeout (two minutes at the moment) in the BitcoinCryptoNetwork is reached the transaction will break, being unable to send the bitcoins and the transactional component wont attempt to resend it.

Exception stack trace: [Outgoing_Intra_Actor_Exception.txt](https://github.com/bitDubai/fermat/files/69050/Outgoing_Intra_Actor_Exception.txt)

@acostarodrigo please assign this to me.

**Comment by acostarodrigo** [comment]
la crypto network no es un componente transaccional, si los bitcoins no se envian, es el método que lo llamo (en este caso el outgoing intra actor) el responsable de reenviar los bitcoins.

**Comment by Yayotron** [comment]
Listo, el cambio solo afectará a este componente transaccional, ya corregí la descripción del issue.
