### ISSUE TITLE
CommunicationNetworkServiceRemoteAgent Pattern bug.

### ISSUE THREAD

**Issue by Yayotron** [bitDubai/fermat#4183]
I'll explain the problem, the cause and the solution.
On all the Fermat Network Service that have the CommunicationNetworkServiceRemoteAgent structure there are two threads running, something like this:

        this.toReceive = new Thread(new Runnable() {
            @Override
            public void run() {
                while (running)
                    processMessageReceived();
            }
        });

        //Create a thread to send the messages
        this.toSend = new Thread(new Runnable() {
            @Override
            public void run() {
                while (running)
                    processMessageToSend();
            }
        });

Every agent have a stop() method that interrupts these threads and is called when the connection is closed and I don't know what others situations.
Now, inside these threads at the end of every method we can find this:

            if(!toReceive.isInterrupted()){
                //Sleep for a time
                Thread.sleep(CommunicationNetworkServiceRemoteAgent.SLEEP_TIME);
            }

            //Sleep for a time
            if (!toReceive.isInterrupted()) {
                toReceive.sleep(WalletStoreNetworkServiceRemoteAgent.SLEEP_TIME);
            }

        } catch (InterruptedException e) {
            toReceive.interrupt();
            System.out.println("CommunicationNetworkServiceRemoteAgent - Thread Interrupted stopped ...  ");
            return;
        } 

When that thread catches an InterruptedException it propagates the interruption to its thread.
What's wrong with that? Interrupting a thread is a "clean" way to stop it, it waits until the thread finish its job then stop its. But that thread has inside a while cycle running that won't let him be stopped, if we combine that with these lines:

            if (!toReceive.isInterrupted()) {
                toReceive.sleep(WalletStoreNetworkServiceRemoteAgent.SLEEP_TIME);
            }

We get several threads running while cycles without stopping, causing this until the application is killed:
![cpu](https://cloud.githubusercontent.com/assets/10087423/12056098/6acb386e-af05-11e5-88b4-ef545162a2ec.png)

Now, the solution is as simple as stop the while cycle when catching the InterruptedException

        catch (InterruptedException e) {
            running = false;
            toReceive.interrupt();
            System.out.println("CommunicationNetworkServiceRemoteAgent - Thread Interrupted stopped ...  ");
        } 

I already tested that and it stops roasting my computer. But that pattern is in several classes (like ten I believe) and I am not sure if I that change will affect something else, and since this is not from my platform I'll let this open at discussion.

@Rart3001 @hendry19901990 @acostarodrigo

**Comment by lnacosta** [comment]
@furszy

**Comment by acostarodrigo** [comment]
Great work Victor!
Roberto has the final answer, but I think we should do the modification in all NS.

**Comment by furszy** [comment]
@Yayotron yo estaba haciendo un hilo genérico para todos los network services que no lo pude terminar por falta de tiempo, ahora lo subo que tambien tenia parte de eso.

**Comment by Rart3001** [comment]
@Yayotron Tu estas en lo correcto, esa instrucción estuvo en su momento pero de tantas modificaciones que se le han realizado, y tomando en consideración que una vez que se pisaron unos cambios en el repositorio seguro se perdieron. Y el cambio lamentablemente hay que hacerlos en todos los NS, ya que cuando hice uno genérico este fue rechazado y fue un error, pero igual es necesario realizar el cambio nuevamente y cada dueño de NS pudiera hacerlo esta modificación y no representaría un gran problema ni trabajo, pero igual yo no tengo problema en hacer el cambio de todos si a los demás se les complica.

**Comment by Yayotron** [comment]
Mucho trabajo tampoco es porque el cambio es pequeño, si no hay nada en lo que esto pueda afectar puedo subir el cambio que tengo hecho local. Son 11 agentes que modifiqué, pero no sé si me dejé alguno por fuera. Si todos los que repiten este patrón tienen el sout de "CommunicationNetworkServiceRemoteAgent - Thread Interrupted stopped ...  " entonces esos son todos.

**Comment by acostarodrigo** [comment]
Subilo, y que cada owner de plataforma lo pruebe.

**Comment by furszy** [comment]
@Yayotron todo cambio que afecte a módulos que no sean tuyos no puede ser considerado ni tomado a la ligera, pensá que si los ns que vos cambiaste están siendo modificados por sus dueños vas a traer conflictos a los demás.

**Comment by acostarodrigo** [comment]
entonces...?

**Comment by Rart3001** [comment]
Yo no veo que traiga mayor problema si se colocaron correctamente, si ya adelanto el trabajo que lo suba y como dice rodrigo que cada uno pruebe su NS.

**Comment by Yayotron** [comment]
@furszy De tomármelo a la ligera subía el cambio de una en vez de iniciar este issue; me parece hacer lo que dice @acostarodrigo de que cada quién lo pruebe en su plataforma, en DAP llevo rato usándolo así y no me ha traído problemas.

**Comment by acostarodrigo** [comment]
cc @nelsonalfo 

@Yayotron subilo y que luego cada Team Lead verifique sus NS.
