### ISSUE TITLE
BCH - CryptoNetwork - Bitcoin - Implementation - New broadcasting schema

### ISSUE THREAD

**Issue by acostarodrigo** [bitDubai/fermat#4200]
#  New broadcasting schema

Change the way we are broadcasting transactions to split the transaction generation and broadcasting into two methods, so that the transactional components can have better controll on sending bitcoins.

 Create and implement the following methods:

in the Bitcoin Vault: 
-------------------------

```java
String generateTransaction (String walletPublicKey, UUID FermatTrId,  CryptoAddress addressTo, long satoshis) throws InsufficientCryptoFundsException, InvalidSendToAddressException,  CryptoTransactionAlreadySentException;
```

Generates a new Bitcoin transaction with all the inputs, outputs and signs the transaction.
The Transaction is stored on the CryptoNetwork.

Will replace the SendBitcoins methods.

in the CryptoNetwork: 
-------------------------

```java
 broadcastTransaction (String txHash) throws CantBroadcastTransactionException, ErrorBroadcastingTransactionException
```

Will broadcast transaction in a new thread. 
* CantBroadcastTransactionException means that it won't be able to broadcast the transaction and needs to be rollbacked.
 
* ErrorBroadcastingException means that somethinf went wrong, but it can be retried,

```java
BroadcastingStatus getBroadcastingStatus (String txHash)
```

returns the current broadcastingStatus for the specified transaction

* BroadcastingStatus includes the amoun of retries and the status. (Broadcasting, Broadcasted, Idle)

The Transactional components of each platform will force the broadcasting and decide to retry or cancel the broadcast of the transaction.

@furszy, @Yayotron 
cc @Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
>The Transaction is stored on the CryptoNetwork.

who gives the transaction to the crypto network?

the vault?

**Comment by acostarodrigo** [comment]
Yes, the vault. The vault creates the transaction and signs it.
Then is given to the CryptoNetwork to be stored in the local blockchain and be broadcasted when requested.
