### ISSUE TITLE
CCP- Reference Wallet - Testing

### ISSUE THREAD

**Issue by nattyco** [bitDubai/fermat#4292]
Al hacer el testeo de la app surgieron estos puntos a corregir:

1- Cambiar botón de help naranja por el nuevo diseño
2- Add Fermat User: si tengo mas de una conexión al tocar el nombre aparecen varios boton azules de add. Si toco el check box no hace nada.
3- Home Tab Receive: las transacciones de extra user se ven duplicadas.
4- Contactos: el contacto de extra user del faucet no muestra el dato address
5- Payment Request: El navigator drawer debe mostrar la cantidad de request recibidos.
6- Payment Request List: si presiono el boton de add abre el nuevo form, al hacer atras se cae la app.
7- Payment Request List: poner la foto real del intra user.
8- Agregar el boton de help a todas las pantallas

@furszy  @Exilum

**Comment by furszy** [comment]
ya hice:
1- Cambiar botón de help naranja por el nuevo diseño
2- Add Fermat User: si tengo mas de una conexión al tocar el nombre aparecen varios boton azules de add. Si toco el check box no hace nada. (sin testear)
5- Payment Request: El navigator drawer debe mostrar la cantidad de request recibidos. (sin testear)
6- Payment Request List: si presiono el boton de add abre el nuevo form, al hacer atras se cae la app.
7- Payment Request List: poner la foto real del intra user.
8- Agregar el boton de help a todas las pantallas

**Comment by nattyco** [comment]
Punto 3: Resuelto por Joaquin.

Punto 4: La address del extra user Faucet este llegando en blanco.

**Comment by nattyco** [comment]
El punto 2 Add Fermat User: sigue pasando cuando hay varios Fermat User

**Comment by nattyco** [comment]
BUG:

La primera vez que entro a la wallet voy a contactos y me aparece la ventana de ayuda donde me da la opción de agregar un contacto intra o extra si presiona Fermat User me lleva a la pantalla de Mis Conexiones en el Community App, si toco una me muestra el profile y no tengo opción de agregar como contacto.
