### ISSUE TITLE
CCP-Sub App Community Connections

### ISSUE THREAD

**Issue by josemanueldsds** [bitDubai/fermat#4329]
A continuacion adjunto una imagen en la cual se puede ver la data de un usuario cuyo publicKey es 046EC7932FDB4EB196D06386162792D8E5A9AB00AF3AC87998CB0F389DD1B598989D908689D311FC92BF27130EB56D80E43659DDC82AA66365B63BB2810146BA99 y su image posee un arreglo de byte de 11, esto causa que no se pueda crear la imagen y mostrar en pantalla 
![screenshot from 2016-01-07 00-04-07](https://cloud.githubusercontent.com/assets/11723355/12162302/5310b4e2-b4d2-11e5-8eab-74b80a2df0d5.png)

**Comment by josemanueldsds** [comment]
@furszy

**Comment by furszy** [comment]
closed
