### ISSUE TITLE
Common Android Bug - Select picture.

### ISSUE THREAD

**Issue by Yayotron** [bitDubai/fermat#4356]
Este issue es replicable el 100% de las veces , lo voy a describir pero no tengo solución, ni idea de qué está pasando: solo hipótesis, espero alguien con más conocimientos de Android que yo pueda tomarlo. Lo voy a escribir todo en español para que se entienda bien.

En varias Sub Apps, Wallets e Identities tenemos que seleccionar una imagen, al seleccionar la opción de la imagen aparecen las opciones Gallery y Camera (con ambas pasa), al seleccionar cualquiera y al tomar cualquier acción después (seleccionar una imagen, tomar una foto o simplemente darle al botón de atrás) empieza el problema; la siguiente vez que se cargue esa vista (Fragment, Adapter, Activity, no sé cuál es) al volver a seleccionar la opción de imagen (Cámara o Galería) se va a abrir dos veces ese diálogo, osea que tenemos que seleccionar dos veces la imagen o tomarnos dos veces la foto, y a la siguiente vez que se cargue la vista no serán dos sino tres veces y así va incrementando.

Lo explico con un ejemplo por si no quedó claro: 
1) En la Asset Factory al crear un nuevo asset seleccionamos la opción de imagen.
2) Seleccionamos  galería y escogemos una foto.
3) Salimos o creamos el asset, da igual, nos devolvemos a la vista anterior.
4) Intentamos crear otro asset, al seleccionar la imagen habrá que seleccionarla dos/tres/n cantidad de veces depende el intento en el que estemos.

Este issue también está presente en otros lugares de Fermat, enlisto los que encontré:
- En la Broker Identity, si intentamos crear varias identities seguidas con una imagen nos pasa.
- En la Bitcoin Wallet, ésta tiene un paso adicional porque el botón está en un dialog, al intentar agregar un external contact seleccionamos la imagen, nos devolvemos al Home y de nuevo a contacto y nos sucede.
- Y obviamente en la Asset Factory con el ejemplo anterior.

Información adicional que encontré debuggeando:
- En la asset factory está llamando al método onContextItemSelected varias veces, depende la cantidad de intento en el que estemos. 
- Este "conteo" se reinicia cuando se cierra la aplicación.
Ya probé:
- Hacer la activity single instance, no funcionó.
- Agregarle al Intent los flags `<Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_SINGLE_TOP>`, con esta opción se muestra una sola ventana, lo que es un avance, pero el método onActivityResult retorna instantáneamente, lo cual es el comportamiento normal según la documentación de Android.
- Crear un singleton del Fragment, tira excepción la aplicación se hace bolita y llora.
- En la FragmentFactory, guardar referencias de los fragments y retornarla, nada pasó...
- En el método SubAppActivity#loadFragment asignarle un tag al fragment y crearlo o buscarlo por ese tag, pero este método ni siquiera es llamado por la Asset Factory...
- Y bastantes validaciones que ninguna funcionó...

@acostarodrigo @furszy @lnacosta @nindriago

**Comment by Luis-Fernando-Molina** [comment]
Por el hecho de que ocurra de manera idéntica en todos lados todo apunta an un problema en el Android Core. El core debe estar llevando un stack de fragmentos cargados y posiblemnte no se elimine este tipo de fragmentos que seguramente son llamadas a otras APPs.

Otra posibilidad pero con menos probabilidades es que haya un problema en el plugin que lleva la estructura de navegación.

@furszy

**Comment by furszy** [comment]
@Luis-Fernando-Molina  el core no lleva ningún stack de fragmentos cargados, lleva solo los que se encuentran en uso (ejemplo: si es con tabs abre el primero, el segundo y el tercero no lo carga hasta no hacer un swipe del primer al segundo, que al pasar al tercero borra el primero, quedando el segundo y tercero activos), esto se hace para que no queden leaks al estar usando las mismas actividades para todo. Tampoco se llaman a otras apps de fermat sin tener permisos. Y por último el plugin de la estructura no aplica en absoluto, ya que como saben al estar llamando a la cámara se está haciendo un callback a la aplicación definida por el dispositivo para tomar fotos, exactamente a la actividad que se encarga de esto, volviendo a la nuestra con la imágen (de ahí viene el método llamado onActivityResult).
En cuanto al problema que estas teniendo, te paso a decir la posible causa: debes estar registrando dos veces el pedido de la camara y al llamarse lo estaría abriendo doble, Cuando vos haces el register de ese OnActivityResult acordate que lo estas registrando a la actividad y yo por más control que le ponga al core siempre van a tener formas de obtener la actividad y manipularla ya que el método es final en android y no se puede reescribir ni bloquear. 
Android está pensado para trabajar conjuntamente actividades con fragmentos pero la arquitectura de fermat nos obliga a dividirlas y ahí debes estar fallando en tu controlador, ya tenemos en nuestro framework métodos optimizados y especializados (la mayor parte anotados en la documentación) para muchos de los casos comunes y eso que pusiste de que se aplica a todas las apps de fermat tampoco sería, yo tengo la posibilidad de la cámara en la bitcoin wallet y la identity y no me pasa eso, necesitaría ver tu código y lo que tienen en esa rama.

#### En conclusión:
@Yayotron deberías estar como el resto de tu equipo en el chat de android, que por cierto vaya a saber porqué está todo el equipo thunder haciendo las mismas pantallas, yo agregué a los que fui viendo que necesitaban una mano como Nerio y Frank, El propósito del chat es que no ocurran estos percances de que te pongas a investigar o pierdas tiempo en cosas que otro ya puede haber pasado y fueron solventadas o quizá cuando se necesite agregar algo al framework,<b> necesitamos avanzar rápido y a paso firme </b>, por lo cual utiliza ese canal ante la más mínima consulta.

Yo estoy todo el día/noche para contestarte lo que necesites.
Saludos.

**Comment by acostarodrigo** [comment]
@furszy Victor no está metido en Android sino resolviendo problemas transaccionales de DAP. 

Como ya lo hizo anteriormente con los network Services, si encuentra un error tiene la excelente iniciativa de investigar y documentar el problema de una forma clara y además ofrecer una solución para ayudarnos a todos.

El canal para comentar este tipo de casos es github a través de un issue, y no tú grupo de skype.

Por si no leiste la explicación detallada para reproducir el issue, no es un problema de DAP ni de Thunder, sino que se reproduce consistentemente en todos lados donde se seleccionan fotos o imágenes.

Por cierto, este no es el lugar para hacer tus comentarios sobre el equipo de Thunder, si ves algún inconveniente tenés la confianza para hablarlo conmigo. En un issue de Github de naturaleza pública, limitate por favor a dar tu opinión del issue en cuestión solamente.

Saludos.
Rodrigo

**Comment by furszy** [comment]
Ahí cambie mi comentario para no herir a nadie, hasta recién estuve hablando con @Yayotron y riendonos xD , lo mejor con todo fermat y feliz de ayudar a resolver los problemas que vayan apareciendo.
Técnicamente y por cuestiones de charla diaria no me sirve hablar por acá y repetir funcionamiento, necesito un ida y vuelta rápido que me lo dá el chat, al igual que ustedes usan slack para comunicarcarse yo uso skype para hablar con el equipo y no veo nada de malo que podamos tener charlas por ahí, hasta tener nuestro propio IRC de fermat android framework.
Hablando del issue exclusivamente, no se repite en mi identity y al estar usando el mismo código en la identity que en la wallet deduje que ocurriría lo mismo, y según lo hablado recién con Victor logré reproducirlo en la wallet en cuestiones muy especificas y no en la identity por lo cual es un caso anormal que ocurre solo en una parte.
Así que nada, Haré el chequeo de eso en la actividad y se hará el chequeo en el controlador que lo llama y se resolverá como siempre.
Saludos.

**Comment by furszy** [comment]
issue resuelto, El problema está en el metodo onActivityResult del fragmento.
Siempre que se le haga un Override a estos métodos de clase, en android, se debe llamar al super.

Cierro el issue y hago los cambios en los fragmetos de todos los equipos.

Saludos.
