### ISSUE TITLE
Crear un banner de gráficos para la  Crypto Broker Wallet

### ISSUE THREAD

**Issue by franklinmarcano1970** [bitDubai/fermat#4563]
@arnaldos @nelsonalfo @Lozadaa Si existe este Issuer donde origino crear este Banner hacer caso omiso a este Issuer, para cerrarlo y etiquetarme en el Issuer correspondiente.

**Comment by arnaldos** [comment]
@franklinmarcano1970 hola franklin este es el caso donde se definio el banner de la crypto broker :+1: https://github.com/bitDubai/fermat-graphic-design/issues/125

**Comment by franklinmarcano1970** [comment]
@arnaldos Perfecto cierro este entonces.
