### ISSUE TITLE
# DAP - Integration Tests - Asset Distribution Scenario #1

### ISSUE THREAD

**Issue by acostarodrigo** [bitDubai/fermat#4615]
# DAP - Integration Tests - Asset Distribution Scenario 1

## Steps:

1. Create Issuer  and User Identity
2. In Asset Factory publish 10 assets.
3. In Asset Issuer Wallet distribute 10 assets to one user.
4. Validate assets are in User Wallet

## Result:

**Comment by pennyxz** [comment]
Test succeeded.
