### ISSUE TITLE
CCP - Reference Wallet -  Severals issues and validations

### ISSUE THREAD

**Issue by Exilum** [bitDubai/fermat#4642]
1.- If the fermat user list is empty the search popup should not appear.
2.- The contact list has been behaving strangely when it is scrolled or when you touch the search button.
3.- if the address of the contact is empty the search and request buttons should not appear.

**Comment by Exilum** [comment]
Point one is fixed.

**Comment by Exilum** [comment]
Point three is fixed.

**Comment by nattyco** [comment]
Pont two fixed
