### ISSUE TITLE
Android api - Settings view - Basic template

### ISSUE THREAD

**Issue by furszy** [bitDubai/fermat#4650]
Se debe desarrollar un template de setting básico para su uso en todas las plataformas de fermat.
El mismo contará con un spinner con los tipos de redes soportadas (MainNet,TestNet,RegTest) para su selección, con un switch el cual activará o desactivará las notificaciones de dicha FermatApp, un switch el cual pondrá las notificaciones en "silencio" (solo con vibración y sin sonido), y con los campos que vayan surgiendo a medida que se va desarrollando el wireframe.

**Comment by furszy** [comment]
@arnaldos @Luis-Fernando-Molina 
Vayan viendo que más podemos incluir en esta vista y como se deberia ver el wireframe

**Comment by Luis-Fernando-Molina** [comment]
No se que tiene que ver las redes con las notificaciones de las APP. Me parece que estas mezclando dos cosas que no tienen relacion... o explicate, no se.

**Comment by furszy** [comment]
Es una pantalla de settings de cualquier wallet, estoy poniendo ahí todo lo que una aplicación dentro de fermat puede configurar,Tener una pantalla con solo un spinner para cambiar de redes no tiene sentido, tiene que haber ciertas configuraciones para dicha aplicación que se deberían hacer en esa pantalla, como cualquier pantalla de "ajustes" de cualquier aplicación de android que tiene notificaciones, lenguaje,etc.
