### ISSUE TITLE
Android lbraries - Chat customView

### ISSUE THREAD

**Issue by furszy** [bitDubai/fermat#4670]
Se debe implementar una ventana como la de un chat, con las burbujas y todo lo que sea necesario para esto.

**Comment by furszy** [comment]
@Luis-Fernando-Molina  Se implementó con éxito. (Necesita UX)
![seleccion_109](https://cloud.githubusercontent.com/assets/5377650/12795893/03027722-ca9b-11e5-8393-905ea26e7411.png)

Próximamente se la pasará a las librerias de android para su posterior uso.

**Comment by Luis-Fernando-Molina** [comment]
Perfect :+1:

**Comment by Luis-Fernando-Molina** [comment]
:+1:  excelente!

**Comment by furszy** [comment]
Completado.
